[build]
  command = "npm run build"
  publish = "public"

# Node.js version for build compatibility
[build.environment]
  NODE_VERSION = "18"

# SPA routing - redirect all routes to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200